import { SCHEMA_VERSION, nowIso, uuid } from './utils.js';
export function hasR2(env){return !!env.RECEIPTS_BUCKET;}
function extForMime(m){return m==='image/webp'?'webp':m==='image/png'?'png':m==='application/pdf'?'pdf':m==='text/csv'?'csv':m.includes('sheet')?'xlsx':'jpg';}
export async function putPrivate(env,key,body,httpMetadata={}){if(!hasR2(env))throw new Error('R2_DISABLED');return env.RECEIPTS_BUCKET.put(key,body,{httpMetadata});}
export async function getPrivate(env,key){if(!hasR2(env))throw new Error('R2_DISABLED');return env.RECEIPTS_BUCKET.get(key);}
export async function deletePrivate(env,keys){if(!hasR2(env))throw new Error('R2_DISABLED');return env.RECEIPTS_BUCKET.delete(keys);}
export async function saveReceipt(repo,env,{transaction_id,bytes,mime_type='image/webp',thumbBytes=null,source='mini_app',keepOriginal=false,originalBytes=null}){if(!hasR2(env))throw new Error('R2_DISABLED');const tx=await repo.getById('Transactions',transaction_id);if(!tx)throw new Error('NOT_FOUND');const rid=uuid(),year=String(tx.transaction_date_iso||new Date().getUTCFullYear()).slice(0,4),ext=extForMime(mime_type);const base=`receipts/${year}/${transaction_id}/${rid}`;const objectKey=`${base}/receipt.${ext}`;await putPrivate(env,objectKey,bytes,{contentType:mime_type,cacheControl:'private, max-age=0'});let thumbKey='';if(thumbBytes){thumbKey=`${base}/thumb.webp`;await putPrivate(env,thumbKey,thumbBytes,{contentType:'image/webp',cacheControl:'private, max-age=0'});}let originalKey='';if(keepOriginal&&originalBytes){originalKey=`${base}/original`;await putPrivate(env,originalKey,originalBytes,{contentType:mime_type,cacheControl:'private, max-age=0'});}const receipt=await repo.insert('Receipts',{receipt_id:rid,transaction_id,object_key:objectKey,thumb_key:thumbKey,mime_type,size_bytes:bytes.byteLength??bytes.size??0,original_key:originalKey,source,ai_status:'none',ai_json:'',created_at:nowIso(),schema_version:SCHEMA_VERSION});await repo.updateById('Transactions',transaction_id,{receipt_count:Number(tx.receipt_count||0)+1});return receipt;}
export async function replaceWithWebp(repo,env,receiptId,{webpBytes,thumbBytes}){const r=await repo.getById('Receipts',receiptId);if(!r)throw new Error('NOT_FOUND');const base=r.object_key.split('/').slice(0,-1).join('/');const next=`${base}/receipt.webp`,thumb=`${base}/thumb.webp`;await putPrivate(env,next,webpBytes,{contentType:'image/webp',cacheControl:'private, max-age=0'});let thumbKey=r.thumb_key||'';if(thumbBytes){await putPrivate(env,thumb,thumbBytes,{contentType:'image/webp',cacheControl:'private, max-age=0'});thumbKey=thumb;}if(r.object_key!==next)await deletePrivate(env,r.object_key);return repo.updateById('Receipts',receiptId,{object_key:next,thumb_key:thumbKey,mime_type:'image/webp',size_bytes:webpBytes.byteLength??0});}
export async function deleteReceipt(repo,env,receiptId){const r=await repo.getById('Receipts',receiptId);if(!r)throw new Error('NOT_FOUND');const keys=[r.object_key,r.thumb_key,r.original_key].filter(Boolean);if(keys.length&&hasR2(env))await deletePrivate(env,keys);const tx=await repo.getById('Transactions',r.transaction_id);await repo.updateById('Receipts',receiptId,{object_key:'',thumb_key:'',original_key:'',ai_status:'deleted'},{action:'delete_file'});if(tx)await repo.updateById('Transactions',tx.transaction_id,{receipt_count:Math.max(0,Number(tx.receipt_count||0)-1)});return true;}
export async function saveInboxFile(repo,env,{name,bytes,mime_type,source='telegram'}){if(!hasR2(env))throw new Error('R2_DISABLED');const id=uuid(),key=`inbox/${new Date().getUTCFullYear()}/${id}/${encodeURIComponent(name||'file')}`;await putPrivate(env,key,bytes,{contentType:mime_type||'application/octet-stream',cacheControl:'private, max-age=0'});const imp=await repo.insert('Imports',{import_id:id,file_name:name||'file',account_id:'',source,object_key:key,status:'uploaded',total_count:0,new_count:0,duplicate_count:0,suspect_count:0,created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});await repo.insert('Inbox',{inbox_id:uuid(),type:'file',entity_type:'import',entity_id:id,title:`فایل: ${name||'بدون نام'}`,payload_json:JSON.stringify({mime_type}),status:'pending',created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});return imp;}
export async function storageStats(repo,env){const [tx,drafts,receipts]=await Promise.all([repo.list('Transactions',{limit:50000}),repo.list('Drafts',{limit:10000}),repo.list('Receipts',{limit:50000})]);let r2_bytes=0,r2_objects=0;if(hasR2(env)){let cursor;do{const x=await env.RECEIPTS_BUCKET.list({prefix:'receipts/',limit:1000,cursor});for(const o of x.objects){r2_bytes+=o.size;r2_objects++;}cursor=x.truncated?x.cursor:undefined;}while(cursor&&r2_objects<10000);}return {transactions:tx.length,drafts:drafts.filter(x=>x.status==='active').length,receipts:receipts.filter(x=>x.ai_status!=='deleted').length,r2_bytes,r2_objects};}
