import { Repository } from './repository.js';
import { migrate } from './schema.js';
import { activeBotSession, createBotAuth, disablePin, pinRequired, pinStatus, revokeBotSessions, setPin } from './auth.js';
import { FinanceService } from './business.js';
import { currentMonthReport, personSummary, projectSummary, queryTransactions, summarize } from './reports.js';
import { handleAiText, confirmAiActions, removeAiAction, reviseAiActions, getAiDraft, extractReceipt, getCapabilities, transcribeAudio, sanitizeAiText, aiErrorText } from './ai.js';
import { telegramCall, webAppUrl, downloadTelegramFile } from './telegram-api.js';
import { saveReceipt, saveInboxFile, getPrivate, putPrivate, deletePrivate, hasR2, probePrivateStorage, storageKind } from './storage.js';
import { parseDateInput, formatJalali, tehranToday } from './jalali.js';
import { advancePastDate } from './recurrence.js';
import { moneyFa, nowIso, normalizeTime, parseMoney, safeJsonParse, SCHEMA_VERSION, tehranTime, tgEscape, uuid, digitsEn, normalizeText, bool, DEFAULT_CURRENCY, currencyCode, fromRial, toRial, userError } from './utils.js';
import { rowsFromCsv, previewImport } from './imports.js';

const OWNER_ONLY='Access Denied';
const TYPES={expense:'خرج',income:'درآمد',transfer:'انتقال',installment_payment:'قسط',debt:'بدهی',receivable:'طلب',refund:'بازپرداخت',adjustment:'اصلاح'};
const kb=rows=>({inline_keyboard:rows});
const btn=(text,callback_data)=>({text,callback_data});
const web=(text,url)=>({text,web_app:{url}});
async function preferredCurrency(repo){return currencyCode(await repo.setting('default_currency',DEFAULT_CURRENCY));}

export function telegramAccessPolicy(ownerId,userId,hasSession,text=''){
  if(String(userId)!==String(ownerId))return'denied';
  if(String(text).startsWith('/setup'))return'setup';
  if(!hasSession&&text==='/start')return'ask_pin';
  if(!hasSession)return'pin';
  return'allowed';
}

function mainKeyboard(env,url){return kb([
  [btn('➕ ثبت','m:add'),btn('🧾 تراکنش‌ها','m:tx')],
  [btn('📊 گزارش','m:report'),btn('📁 پروژه‌ها','m:projects')],
  [btn('💳 اقساط','m:installments'),btn('👥 اشخاص','m:people')],
  [btn('🤖 دستیار','m:ai'),web('🌐 داشبورد',webAppUrl(env,url))],
  [btn('⚙️ تنظیمات','m:settings')]
]);}
function menuText(){return'💰 <b>مدیریت مالی</b>\n\nیک گزینه را انتخاب کنید.';}
async function safeCall(env,method,payload){try{return await telegramCall(env,method,payload);}catch(error){if(method.startsWith('editMessage')&&String(error.description||'').includes('message is not modified'))return null;throw error;}}
async function panel(env,chatId,messageId,text,replyMarkup){const payload={chat_id:chatId,text,parse_mode:'HTML',disable_web_page_preview:true,reply_markup:replyMarkup};if(messageId){payload.message_id=messageId;await safeCall(env,'editMessageText',payload);return messageId;}const message=await telegramCall(env,'sendMessage',payload);return message.message_id;}
async function delIncoming(env,chatId,messageId){try{await telegramCall(env,'deleteMessage',{chat_id:chatId,message_id:messageId});}catch{}}
async function answerCb(env,id,text=''){try{await telegramCall(env,'answerCallbackQuery',{callback_query_id:id,text,show_alert:false});}catch{}}
async function showMain(env,chatId,messageId,url){return panel(env,chatId,messageId,menuText(),mainKeyboard(env,url));}

async function activeDraft(repo,kind){const rows=await repo.list('Drafts',{limit:1000});return rows.filter(x=>x.kind===kind&&x.status==='active'&&(!x.expires_at||x.expires_at>nowIso())).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0]||null;}
async function createDraft(repo,kind,state,expiresHours=72){return repo.insert('Drafts',{draft_id:uuid(),kind,owner_telegram_id:String(repo.env.OWNER_TELEGRAM_ID),state_json:JSON.stringify(state),status:'active',created_at:nowIso(),updated_at:nowIso(),expires_at:new Date(Date.now()+expiresHours*3600e3).toISOString(),schema_version:SCHEMA_VERSION},{audit:false});}
async function updateDraft(repo,draft,state){return repo.updateById('Drafts',draft.draft_id,{state_json:JSON.stringify(state),updated_at:nowIso()},{audit:false});}
async function loadState(repo,kind){const draft=await activeDraft(repo,kind);return draft?{draft,state:safeJsonParse(draft.state_json,{})}:null;}
async function closeDraft(repo,kind,status='closed'){const draft=await activeDraft(repo,kind);if(draft)await repo.updateById('Drafts',draft.draft_id,{status},{audit:false});}
async function setBotMode(repo,state){const old=await activeDraft(repo,'bot_mode');if(old)return updateDraft(repo,old,state);return createDraft(repo,'bot_mode',state,720);}
async function clearBotMode(repo){await closeDraft(repo,'bot_mode','closed');}

function previewReceiptCount(state){return(state.pending_receipts||[]).length+Number(state.receipt_count_existing||0);}
function formatTxPreview(state){
  const lines=['🧾 <b>پیش‌نمایش تراکنش</b>',`نوع: ${TYPES[state.type]||state.type||'—'}`,`مبلغ: <b>${state.amount!==undefined?moneyFa(state.amount,state.currency||DEFAULT_CURRENCY):'—'}</b>`];
  if(state.fee_amount)lines.push(`کارمزد: ${moneyFa(state.fee_amount,state.currency||DEFAULT_CURRENCY)}`);
  if(state.transaction_date_iso)lines.push(`تاریخ: ${tgEscape(formatJalali(state.transaction_date_iso))}`);
  if(state.transaction_time)lines.push(`ساعت: ${tgEscape(state.transaction_time)}`);
  if(state.description)lines.push(`شرح: ${tgEscape(state.description)}`);
  if(state.account_name)lines.push(`حساب: ${tgEscape(state.account_name)}`);
  if(state.destination_account_name)lines.push(`مقصد: ${tgEscape(state.destination_account_name)}`);
  if(state.category_name)lines.push(`دسته: ${tgEscape(state.category_name)}`);
  if(state.person_name)lines.push(`شخص: ${tgEscape(state.person_name)}`);
  if(state.project_name)lines.push(`پروژه: ${tgEscape(state.project_name)}`);
  if(state.merchant_name)lines.push(`فروشنده: ${tgEscape(state.merchant_name)}`);
  if(state.tag_names?.length)lines.push(`برچسب: ${state.tag_names.map(x=>'#'+tgEscape(x)).join(' ')}`);
  if(state.note)lines.push(`یادداشت: ${tgEscape(state.note)}`);
  if(state.tracking_number)lines.push(`پیگیری: ${tgEscape(state.tracking_number)}`);
  if(state.reference_number)lines.push(`مرجع: ${tgEscape(state.reference_number)}`);
  if(previewReceiptCount(state))lines.push(`فیش: ${previewReceiptCount(state).toLocaleString('fa-IR')} عدد`);
  return lines.join('\n');
}
function previewKb(){return kb([[btn('✅ تأیید','w:confirm'),btn('✏️ ویرایش','w:edit')],[btn('جزئیات بیشتر','w:more')],[btn('❌ لغو','w:cancel')]]);}
async function showDraftResume(repo,env,chatId,messageId,url){const flow=await loadState(repo,'transaction_wizard');if(!flow)return false;flow.state.message_id=messageId||flow.state.message_id||null;await updateDraft(repo,flow.draft,flow.state);await panel(env,chatId,messageId,'📝 یک تراکنش نیمه‌کاره دارید.',kb([[btn('▶️ ادامه','draft:resume'),btn('🗑 حذف','draft:discard')],[btn('➕ ثبت جدید','draft:new')],[btn('🏠 منو','m:home')]]));return true;}
async function resumeWizard(repo,env,chatId,messageId,url){const flow=await loadState(repo,'transaction_wizard');if(!flow)return showMain(env,chatId,messageId,url);flow.state.message_id=messageId;await updateDraft(repo,flow.draft,flow.state);const s=flow.state;if(s.awaiting==='amount'||s.awaiting==='installment_amount')return askAmount(env,chatId,messageId,s.installment_id?Number(s.default_installment_amount||0):0,s.currency||DEFAULT_CURRENCY);if(s.awaiting==='date')return panel(env,chatId,messageId,'📅 تاریخ شمسی یا میلادی را بفرستید.',kb([[btn('امروز','w:date:today'),btn('دیروز','w:date:yesterday')],[btn('❌ لغو','w:cancel')]]));if(s.awaiting==='time')return askTime(env,chatId,messageId);if(s.awaiting==='description')return askDescription(env,chatId,messageId);if(s.awaiting==='receipt')return showReceiptCapture(env,chatId,messageId,s);return panel(env,chatId,messageId,formatTxPreview(s),previewKb());}

async function namedRows(repo,sheet){return(await repo.list(sheet,{limit:500,filter:x=>!bool(x.is_deleted)&&!bool(x.archived)})).sort((a,b)=>Number(bool(b.favorite))-Number(bool(a.favorite))||String(a.name||a.title||'').localeCompare(String(b.name||b.title||''),'fa'));}
async function chooseAccounts(repo,env,chatId,messageId,url,{allowNone=false}={}){const rows=await namedRows(repo,'Accounts'),buttons=rows.slice(0,12).map(a=>[btn(`${a.icon||'💳'} ${a.name}`,`w:acct:${a.account_id}`)]);if(allowNone)buttons.push([btn('بدون حساب','w:acct:none')]);buttons.push([web('مدیریت حساب‌ها',webAppUrl(env,url))],[btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'💳 <b>حساب را انتخاب کنید</b>',kb(buttons));}
async function chooseCategories(repo,env,chatId,messageId){const rows=await namedRows(repo,'Categories'),buttons=[];for(let i=0;i<Math.min(rows.length,14);i+=2)buttons.push(rows.slice(i,i+2).map(c=>btn(`${c.icon||'•'} ${c.name}`,`w:cat:${c.category_id}`)));buttons.push([btn('رد کردن','w:cat:skip'),btn('➕ دسته جدید','cat:new:wizard')],[btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'🏷 <b>دسته‌بندی</b>',kb(buttons));}
async function chooseDestination(repo,env,chatId,messageId,sourceId){const rows=(await namedRows(repo,'Accounts')).filter(x=>x.account_id!==sourceId);return panel(env,chatId,messageId,'➡️ <b>حساب مقصد را انتخاب کنید</b>',kb([...rows.slice(0,12).map(a=>[btn(`${a.icon||'💳'} ${a.name}`,`w:dest:${a.account_id}`)]),[btn('❌ لغو','w:cancel')]]));}
async function choosePeople(repo,env,chatId,messageId,context='core'){const rows=await namedRows(repo,'People'),buttons=rows.slice(0,12).map(p=>[btn(p.name,`w:person:${p.person_id}`)]);buttons.push([btn('➕ شخص جدید',`w:newperson:${context}`)]);if(context==='advanced')buttons.push([btn('پاک کردن شخص','w:person:clear'),btn('⬅️ بازگشت','w:more')]);else buttons.push([btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'👤 <b>شخص را انتخاب کنید</b>',kb(buttons));}
async function chooseRefundOrigin(repo,env,chatId,messageId){const rows=await repo.list('Transactions',{limit:1000,includeDeleted:false,filter:x=>['expense','installment_payment','receivable'].includes(x.type)&&String(x.status||'confirmed')==='confirmed',sort:(a,b)=>String(b.transaction_date_iso).localeCompare(String(a.transaction_date_iso))});const buttons=rows.slice(0,10).map(t=>[btn(`${t.description||TYPES[t.type]} — ${moneyFa(t.amount)}`,`w:refund:${t.transaction_id}`)]);buttons.push([btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'↩️ <b>تراکنش اصلی بازپرداخت را انتخاب کنید</b>',kb(buttons));}
async function chooseInstallmentPlan(repo,env,chatId,messageId,url){const rows=await repo.list('Installments',{limit:500,filter:x=>x.status!=='completed'&&!bool(x.is_deleted)&&!bool(x.archived)}),buttons=rows.slice(0,12).map(p=>[btn(`${p.title} — ${moneyFa(p.default_installment_amount)}`,`w:inst:${p.installment_id}`)]);buttons.push([web('مدیریت اقساط',webAppUrl(env,url))],[btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'💳 <b>کدام قسط؟</b>',kb(buttons));}
async function askAmount(env,chatId,messageId,defaultAmount=0,currency=DEFAULT_CURRENCY){const rows=[],unit=currencyCode(currency);if(defaultAmount>0)rows.push([btn(`مبلغ پیش‌فرض: ${moneyFa(defaultAmount,unit)}`,'w:amount:default')]);rows.push([btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,`💰 مبلغ را به ${unit==='TOMAN'?'تومان':'ریال'} بفرستید.`,kb(rows));}
async function askDate(env,chatId,messageId){return panel(env,chatId,messageId,'📅 <b>تاریخ تراکنش</b>',kb([[btn('امروز','w:date:today'),btn('دیروز','w:date:yesterday')],[btn('تاریخ دستی','w:date:manual')],[btn('❌ لغو','w:cancel')]]));}
async function askTime(env,chatId,messageId){return panel(env,chatId,messageId,'🕐 <b>ساعت تراکنش</b>',kb([[btn('الان','w:time:now')],[btn('ساعت دستی','w:time:manual')],[btn('❌ لغو','w:cancel')]]));}
async function askDescription(env,chatId,messageId){return panel(env,chatId,messageId,'✏️ توضیح را بفرستید یا رد کنید.',kb([[btn('رد کردن','w:desc:skip')],[btn('❌ لغو','w:cancel')]]));}
async function showAdvanced(repo,env,chatId,messageId,state){return panel(env,chatId,messageId,'🔎 <b>جزئیات بیشتر</b>',kb([
  [btn(`👤 شخص${state.person_name?' ✓':''}`,'w:more:person'),btn(`📁 پروژه${state.project_name?' ✓':''}`,'w:more:project')],
  [btn(`🏪 فروشنده${state.merchant_name?' ✓':''}`,'w:more:merchant'),btn(`🏷 برچسب${state.tag_names?.length?' ✓':''}`,'w:more:tags')],
  [btn(`💸 کارمزد${state.fee_amount?' ✓':''}`,'w:more:fee'),btn(`📝 یادداشت${state.note?' ✓':''}`,'w:more:note')],
  [btn(`🔢 پیگیری${state.tracking_number?' ✓':''}`,'w:more:tracking'),btn(`🔖 مرجع${state.reference_number?' ✓':''}`,'w:more:reference')],
  [btn(`📷 فیش${previewReceiptCount(state)?` (${previewReceiptCount(state)})`:''}`,'w:more:receipt')],[btn('⬅️ پیش‌نمایش','w:preview')]
]));}
async function showEntityChoices(repo,env,chatId,messageId,sheet,idField,prefix,title,newCallback,clearCallback){const rows=await namedRows(repo,sheet),buttons=rows.slice(0,12).map(x=>[btn(x.name||x.title,`${prefix}${x[idField]}`)]);if(newCallback)buttons.push([btn('➕ جدید',newCallback)]);if(clearCallback)buttons.push([btn('پاک کردن',clearCallback)]);buttons.push([btn('⬅️ بازگشت','w:more')]);return panel(env,chatId,messageId,`<b>${title}</b>`,kb(buttons));}
async function showTags(repo,env,chatId,messageId,state){const rows=await namedRows(repo,'Tags'),selected=new Set(state.tag_ids||[]),buttons=rows.slice(0,14).map(t=>[btn(`${selected.has(t.tag_id)?'✅':'▫️'} ${t.name}`,`w:tag:${t.tag_id}`)]);buttons.push([btn('تمام','w:more')]);return panel(env,chatId,messageId,'🏷 <b>برچسب‌ها</b>',kb(buttons));}
async function showReceiptCapture(env,chatId,messageId,state){const count=(state.pending_receipts||[]).length;return panel(env,chatId,messageId,hasR2(env)?`📷 عکس یا فایل تصویری فیش را بفرستید.\nفیش‌های آماده: ${count.toLocaleString('fa-IR')}`:'⚠️ فضای فایل تنظیم نشده است.',kb([[btn('✅ پایان افزودن فیش','w:receipt:done')],[btn('⬅️ بازگشت','w:more')]]));}

async function startWizard(repo,env,chatId,messageId,url,force=false,prefill={}){
  if(!force&&await activeDraft(repo,'transaction_wizard'))return showDraftResume(repo,env,chatId,messageId,url);
  if(force)await closeDraft(repo,'transaction_wizard','discarded');
  const currency=await preferredCurrency(repo),state={type:'',amount:undefined,fee_amount:0,currency,transaction_date_iso:'',description:'',tag_ids:[],tag_names:[],pending_receipts:[],message_id:messageId,...prefill};await createDraft(repo,'transaction_wizard',state);
  const templates=(await namedRows(repo,'Templates')).filter(x=>bool(x.favorite)).slice(0,3),rows=[[btn('خرج','w:type:expense'),btn('درآمد','w:type:income')],[btn('انتقال','w:type:transfer'),btn('قسط','w:type:installment_payment')],[btn('بدهی','w:type:debt'),btn('طلب','w:type:receivable')],[btn('بازپرداخت','w:type:refund'),btn('اصلاح','w:type:adjustment')]];
  for(const t of templates)rows.push([btn(`⚡ ${t.name}`,`tpl:${t.template_id}`)]);rows.push([btn('❌ لغو','w:cancel')]);return panel(env,chatId,messageId,'➕ <b>نوع تراکنش</b>',kb(rows));
}
async function hydrateTemplate(repo,state,template){
  state.type=template.type||'expense';state.account_id=template.account_id||'';state.category_id=template.category_id||'';state.merchant_id=template.merchant_id||'';state.project_id=template.project_id||'';state.description=template.description||'';state.tag_ids=safeJsonParse(template.tags_json,[])||[];
  const refs=[['Accounts','account_id','account_id','account_name'],['Categories','category_id','category_id','category_name'],['Merchants','merchant_id','merchant_id','merchant_name'],['Projects','project_id','project_id','project_name']];for(const [sheet,idField,key,nameKey] of refs)if(state[key]){const row=await repo.getById(sheet,state[key]);state[nameKey]=row?.name||row?.title||'';}
  if(state.tag_ids.length){const tags=await repo.list('Tags',{limit:500});state.tag_names=tags.filter(x=>state.tag_ids.includes(x.tag_id)).map(x=>x.name);}return state;
}
async function afterAmount(repo,env,chatId,messageId,url,flow){const s=flow.state;if(s.installment_id)return afterInstallmentAmount(repo,env,chatId,messageId,url,flow);if(s.type==='refund')return chooseRefundOrigin(repo,env,chatId,messageId);if(['debt','receivable'].includes(s.type)&&!s.person_id)return choosePeople(repo,env,chatId,messageId,'core');return chooseAccounts(repo,env,chatId,messageId,url,{allowNone:s.type==='debt'});}
async function afterInstallmentAmount(repo,env,chatId,messageId,url,flow){const s=flow.state;if(s.account_id){s.transaction_date_iso=s.transaction_date_iso||parseDateInput('امروز');await updateDraft(repo,flow.draft,s);return panel(env,chatId,messageId,formatTxPreview(s),previewKb());}return chooseAccounts(repo,env,chatId,messageId,url);}
async function afterPerson(repo,env,chatId,messageId,url,flow,context='core'){const s=flow.state;if(context==='advanced'){if(s.type==='expense')return panel(env,chatId,messageId,'👤 این مبلغ را از این شخص پس می‌گیرید؟',kb([[btn('بله، طلب است','w:personreturn:yes'),btn('خیر، خرج شخصی','w:personreturn:no')],[btn('⬅️ بازگشت','w:more')]]));return showAdvanced(repo,env,chatId,messageId,s);}return chooseAccounts(repo,env,chatId,messageId,url,{allowNone:s.type==='debt'});}
async function afterAccount(repo,env,chatId,messageId,url,flow){const s=flow.state;if(s.type==='transfer')return chooseDestination(repo,env,chatId,messageId,s.account_id);if(s.installment_id){s.transaction_date_iso=s.transaction_date_iso||parseDateInput('امروز');await updateDraft(repo,flow.draft,s);return panel(env,chatId,messageId,formatTxPreview(s),previewKb());}return chooseCategories(repo,env,chatId,messageId);}
async function afterCategory(repo,env,chatId,messageId,flow){return askDate(env,chatId,messageId);}
async function afterDate(repo,env,chatId,messageId,flow){flow.state.awaiting='time';await updateDraft(repo,flow.draft,flow.state);return askTime(env,chatId,messageId);}
async function afterTime(repo,env,chatId,messageId,flow){flow.state.awaiting='description';await updateDraft(repo,flow.draft,flow.state);return askDescription(env,chatId,messageId);}

function quickParse(text){const value=digitsEn(text),match=value.match(/(?:^|\s)(\d[\d,٬،_]*)(?:\s|$)/);if(!match)return null;let amount;try{amount=parseMoney(match[1]);}catch{return null;}if(amount<=0)return null;const description=value.replace(match[1],'').replace(/\s+/g,' ').trim();return{amount,description};}
async function quickEntry(repo,env,chatId,text,url){const parsed=quickParse(text);if(!parsed)return false;const finance=new FinanceService(repo,'owner'),defaultAccount=await repo.setting('default_account',''),accounts=await namedRows(repo,'Accounts');let account=accounts.find(x=>x.account_id===defaultAccount);if(!account&&accounts.length===1)account=accounts[0];let state=await finance.applyRules({type:'expense',amount:parsed.amount,description:parsed.description,transaction_date_iso:parseDateInput('امروز'),account_id:account?.account_id||'',fee_amount:0,tag_ids:[],tag_names:[],pending_receipts:[]});
  if(state.account_id){const a=await repo.getById('Accounts',state.account_id);state.account_name=a?.name||'';}if(state.category_id){const c=await repo.getById('Categories',state.category_id);state.category_name=c?.name||'';}if(state.merchant_id){const m=await repo.getById('Merchants',state.merchant_id);state.merchant_name=m?.name||'';}const message=await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🧾 در حال آماده‌سازی ثبت سریع…'});state.message_id=message.message_id;await closeDraft(repo,'transaction_wizard','replaced');await createDraft(repo,'transaction_wizard',state);const flow=await loadState(repo,'transaction_wizard');if(!state.account_id)await chooseAccounts(repo,env,chatId,message.message_id,url);else await panel(env,chatId,message.message_id,formatTxPreview(state),previewKb());return true;}

function txListText(rows){if(!rows.length)return'🧾 تراکنشی ثبت نشده است.';return'🧾 <b>آخرین تراکنش‌ها</b>\n\n'+rows.slice(0,8).map(t=>`${t.type==='income'?'🟢':t.type==='transfer'?'🔵':'🔸'} ${tgEscape(t.description||TYPES[t.type]||'تراکنش')} — <b>${moneyFa(t.amount)}</b>\n${tgEscape(t.transaction_date||'')}`).join('\n\n');}
async function categoryMenu(repo,env,chatId,messageId){const rows=await namedRows(repo,'Categories'),buttons=rows.slice(0,12).map(c=>[btn(`${bool(c.favorite)?'⭐ ':''}${c.name}`,`cat:view:${c.category_id}`)]);buttons.push([btn('➕ دسته جدید','cat:new:menu')],[btn('⬅️ تنظیمات','m:settings')]);return panel(env,chatId,messageId,'🏷 <b>دسته‌بندی‌ها</b>',kb(buttons));}
async function setupHealth(repo,env){const required=['TELEGRAM_BOT_TOKEN','OWNER_TELEGRAM_ID','SPREADSHEET_ID','GOOGLE_SERVICE_ACCOUNT_JSON','SESSION_SECRET'],missing=required.filter(k=>!env[k]);let google=false,telegram=false,storage={ok:false,kind:storageKind(env)},ai={configured:!!env.OPENROUTER_API_KEY,text:false,vision:false,audio:false,file:false};try{await repo.spreadsheetInfo();google=true;}catch{}try{await telegramCall(env,'getMe',{});telegram=true;}catch{}storage=await probePrivateStorage(env);try{const c=await getCapabilities(repo,env);ai={configured:c.configured,text:c.text,vision:c.vision,audio:c.audio,file:c.file,model:c.models?.text?.id||'',requested_model:c.requested_models?.text||'',fallback_used:!!c.fallback_used,error:c.error||''};}catch{}return{missing,google,telegram,storage,ai};}
function healthText(h){const label=h.storage.kind==='kv'?'Cloudflare KV':h.storage.kind==='r2'?'Cloudflare R2':'فضای فایل';return`🩺 <b>وضعیت سیستم</b>\n${h.google?'✅':'❌'} Google Sheets\n${h.telegram?'✅':'❌'} Telegram\n${h.storage.ok?'✅':'⚠️'} ${label}${h.storage.ok?'':' — تنظیم نشده یا در دسترس نیست'}\n${h.ai.text?'✅':h.ai.configured?'⚠️':'⚠️'} OpenRouter Text${h.ai.configured?'':' — تنظیم نشده'}${h.ai.text&&h.ai.model?` — ${h.ai.model}${h.ai.fallback_used?' (fallback)':''}`:''}${!h.ai.text&&h.ai.error?' — خطای اتصال/کلید':''}\n${h.ai.vision?'✅':'▫️'} Vision\n${h.ai.audio?'✅':'▫️'} Audio\n${h.ai.file?'✅':'▫️'} File\n${h.missing.length?'❌ Secretهای لازم ناقص‌اند: '+h.missing.join(', '):'✅ Secretهای اصلی تنظیم‌اند'}`;}

export async function handleTelegram(request,env){
  let update;try{update=await request.json();}catch{return new Response('ok');}
  const userId=String(update.message?.from?.id??update.callback_query?.from?.id??''),chatId=String(update.message?.chat?.id??update.callback_query?.message?.chat?.id??userId);
  if(userId!==String(env.OWNER_TELEGRAM_ID)){if(update.callback_query)await answerCb(env,update.callback_query.id,OWNER_ONLY);else if(chatId)await telegramCall(env,'sendMessage',{chat_id:chatId,text:OWNER_ONLY}).catch(()=>{});return new Response('ok');}
  const repo=new Repository(env,'telegram');
  if(update.message?.text?.startsWith('/setup')){
    try{const migration=await migrate(repo),health=await setupHealth(repo,env);await telegramCall(env,'sendMessage',{chat_id:chatId,text:`✅ Setup انجام شد\nSchema: v${migration.schema_version}\nSheets: ${migration.sheets}\n\n${healthText(health)}`,parse_mode:'HTML'});}catch{await telegramCall(env,'sendMessage',{chat_id:chatId,text:'❌ اتصال Google Sheets یا Schema بررسی شود.'}).catch(()=>{});}return new Response('ok');
  }
  try{const done=await repo.findOne('ProcessedUpdates',x=>String(x.update_id)===String(update.update_id));if(done)return new Response('ok');await repo.insert('ProcessedUpdates',{processed_id:uuid(),update_id:String(update.update_id),created_at:nowIso(),schema_version:SCHEMA_VERSION},{audit:false});}catch{}
  let session=null;try{session=await activeBotSession(repo,userId);}catch{}
  if(!session&&!await pinRequired(repo,env)){try{await createBotAuth(repo,env,userId,'');session=await activeBotSession(repo,userId);}catch{}}
  if(!session){
    if(update.callback_query){await answerCb(env,update.callback_query.id,'ابتدا رمز را وارد کنید.');return new Response('ok');}
    const text=update.message?.text||'';if(text==='/start'){await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🔐 رمز ورود را ارسال کنید.'});return new Response('ok');}
    if(!text){await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🔐 ابتدا رمز ورود را وارد کنید.'});return new Response('ok');}
    try{await createBotAuth(repo,env,userId,text);await delIncoming(env,chatId,update.message.message_id);const msg=await telegramCall(env,'sendMessage',{chat_id:chatId,text:'✅ ورود موفق بود.'});if(!await showDraftResume(repo,env,chatId,msg.message_id,request.url))await showMain(env,chatId,msg.message_id,request.url);}catch(error){await delIncoming(env,chatId,update.message.message_id);await telegramCall(env,'sendMessage',{chat_id:chatId,text:error.message==='PIN_LOCKED'?'🔒 ورود موقتاً قفل شده است.':'❌ رمز نادرست است.'});}return new Response('ok');
  }
  try{
    if(update.callback_query)await handleCallback(update.callback_query,repo,env,request.url);
    else if(update.message?.photo)await handlePhoto(update.message,repo,env,request.url);
    else if(update.message?.document)await handleDocument(update.message,repo,env,request.url);
    else if(update.message?.voice)await handleVoice(update.message,repo,env,request.url);
    else if(update.message?.web_app_data)await telegramCall(env,'sendMessage',{chat_id:chatId,text:'✅ دریافت شد.'});
    else if(update.message?.text)await handleText(update.message,repo,env,request.url);
  }catch{await telegramCall(env,'sendMessage',{chat_id:chatId,text:'⚠️ عملیات انجام نشد. دوباره تلاش کنید.'}).catch(()=>{});}
  return new Response('ok');
}

async function handleText(msg,repo,env,url){
  const chatId=String(msg.chat.id),text=msg.text.trim();
  if(text==='/start'||text==='/menu'){await clearBotMode(repo);if(!await showDraftResume(repo,env,chatId,null,url))await showMain(env,chatId,null,url);return;}
  if(text==='/lock'){await revokeBotSessions(repo,msg.from.id);await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🔒 قفل شد.'});return;}
  const flow=await loadState(repo,'transaction_wizard');
  if(flow){
    const s=flow.state;
    try{
      if(s.awaiting==='amount'||s.awaiting==='installment_amount'||s.awaiting==='debt_partial_amount'){
        s.amount=parseMoney(text);if(s.amount<=0)throw new Error('INVALID_MONEY');s.awaiting='';await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);if(s.debt_id)return chooseAccounts(repo,env,chatId,s.message_id,url);return afterAmount(repo,env,chatId,s.message_id,url,flow);
      }
      if(s.awaiting==='date'){s.transaction_date_iso=parseDateInput(text);s.awaiting='';await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return afterDate(repo,env,chatId,s.message_id,flow);}
      if(s.awaiting==='time'){s.transaction_time=normalizeTime(text);s.awaiting='';await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return afterTime(repo,env,chatId,s.message_id,flow);}
      if(s.awaiting==='description'){s.description=text;s.awaiting='';await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return panel(env,chatId,s.message_id,formatTxPreview(s),previewKb());}
      if(['fee_amount','note','tracking_number','reference_number'].includes(s.awaiting)){const field=s.awaiting;s[field]=field==='fee_amount'?parseMoney(text):text;s.awaiting='';await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return showAdvanced(repo,env,chatId,s.message_id,s);}
      if(['new_person_core','new_person_advanced','new_project','new_merchant'].includes(s.awaiting)){
        const mode=s.awaiting;s.awaiting='';if(mode.startsWith('new_person')){const row=await repo.insert('People',{person_id:uuid(),name:text,phone:'',note:'',color:'',favorite:false,archived:false,created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});s.person_id=row.person_id;s.person_name=row.name;await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return afterPerson(repo,env,chatId,s.message_id,url,flow,mode.endsWith('advanced')?'advanced':'core');}
        if(mode==='new_project'){const row=await repo.insert('Projects',{project_id:uuid(),name:text,description:'',icon:'',color:'',budget:'',start_date:'',end_date:'',status:'active',archived:false,favorite:false,created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});s.project_id=row.project_id;s.project_name=row.name;}
        if(mode==='new_merchant'){const row=await repo.insert('Merchants',{merchant_id:uuid(),name:text,default_category_id:'',default_project_id:'',default_tags_json:'[]',icon:'',color:'',favorite:false,archived:false,created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});s.merchant_id=row.merchant_id;s.merchant_name=row.name;}
        await updateDraft(repo,flow.draft,s);await delIncoming(env,chatId,msg.message_id);return showAdvanced(repo,env,chatId,s.message_id,s);
      }
      if(s.awaiting==='receipt'){await delIncoming(env,chatId,msg.message_id);return showReceiptCapture(env,chatId,s.message_id,s);}
      await delIncoming(env,chatId,msg.message_id);return panel(env,chatId,s.message_id,'📝 این پیش‌نویس هنوز باز است.',previewKb());
    }catch{await delIncoming(env,chatId,msg.message_id);return panel(env,chatId,s.message_id,'ورودی معتبر نیست. دوباره وارد کنید.',kb([[btn('❌ لغو','w:cancel')]]));}
  }
  const input=await loadState(repo,'bot_input');
  if(input){
    await delIncoming(env,chatId,msg.message_id);const state=input.state;
    if(state.action==='pin_set'){try{await setPin(repo,env,text);await repo.updateById('Drafts',input.draft.draft_id,{status:'done'},{audit:false});return telegramCall(env,'sendMessage',{chat_id:chatId,text:'✅ رمز جدید ذخیره و فعال شد. پیام رمز هم حذف شد.'});}catch{return telegramCall(env,'sendMessage',{chat_id:chatId,text:'رمز باید بین ۴ تا ۳۲ کاراکتر باشد. دوباره ارسال کنید.'});}}
    if(state.action==='category_new'){
      const category=await repo.insert('Categories',{category_id:uuid(),name:text,icon:'',color:'',type:'expense',favorite:false,archived:false,created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});await repo.updateById('Drafts',input.draft.draft_id,{status:'done'},{audit:false});
      if(state.return==='wizard'){const w=await loadState(repo,'transaction_wizard');if(w){w.state.category_id=category.category_id;w.state.category_name=category.name;await updateDraft(repo,w.draft,w.state);return askDate(env,chatId,w.state.message_id);}}return categoryMenu(repo,env,chatId,state.message_id);
    }
    if(state.action==='category_rename'){await repo.updateById('Categories',state.category_id,{name:text});await repo.updateById('Drafts',input.draft.draft_id,{status:'done'},{audit:false});return categoryMenu(repo,env,chatId,state.message_id);}
    if(state.action==='ai_choice'){const choice=state.options?.[Number(state.index)]||text;await repo.updateById('Drafts',input.draft.draft_id,{status:'done'},{audit:false});const result=await handleAiText(repo,env,`${state.original_text}\nانتخاب من: ${choice}`);return showAiResult(repo,env,chatId,state.message_id,result,url);}
  }
  const mode=await loadState(repo,'bot_mode');
  if(mode?.state.mode==='ai_edit'){
    const history=Array.isArray(mode.state.history)?mode.state.history:[],draftId=mode.state.draft_id;let result;await delIncoming(env,chatId,msg.message_id);await panel(env,chatId,mode.state.message_id,'🤖 <b>دارم پیشنهاد را اصلاح می‌کنم…</b>',kb([[btn('❌ لغو پیشنهاد',`aicancel:${draftId}`)]]));
    try{result=await reviseAiActions(repo,env,draftId,text,history);}catch(error){return panel(env,chatId,mode.state.message_id,`🤖 ${tgEscape(aiErrorText(error))}

پیشنهاد قبلی هنوز دست‌نخورده است.`,kb([[btn('⬅️ بازگشت به پیشنهاد',`aiback:${draftId}`),btn('❌ لغو پیشنهاد',`aicancel:${draftId}`)]]));}
    mode.state.mode='ai';mode.state.draft_id='';mode.state.history=[...history,{role:'user',content:`اصلاح پیشنهاد: ${text}`},{role:'assistant',content:result.kind==='actions'?'پیشنهاد اصلاح شد.':String(result.text||'برای اصلاح، توضیح بیشتری لازم است.')}].slice(-12);await updateDraft(repo,mode.draft,mode.state);
    return showAiResult(repo,env,chatId,mode.state.message_id,result,url,text);
  }
  if(mode?.state.mode==='ai'){
    const history=Array.isArray(mode.state.history)?mode.state.history:[];let result;await delIncoming(env,chatId,msg.message_id);await panel(env,chatId,mode.state.message_id,'🤖 <b>دارم بررسی می‌کنم…</b>',kb([[btn('خروج از دستیار','ai:exit')]]));
    try{result=await handleAiText(repo,env,text,history);}catch(error){return panel(env,chatId,mode.state.message_id,`🤖 ${tgEscape(aiErrorText(error))}`,kb([[btn('خروج از دستیار','ai:exit')]]));}
    const assistant=result.kind==='actions'?`${result.actions.length} اقدام پیشنهادی برای تأیید آماده شد.`:result.kind==='split'?'محاسبه دنگ انجام شد.':String(result.text||'پاسخ آماده شد.');
    mode.state.history=[...history,{role:'user',content:text},{role:'assistant',content:assistant}].slice(-12);await updateDraft(repo,mode.draft,mode.state);
    return showAiResult(repo,env,chatId,mode.state.message_id,result,url,text);
  }
  if(await quickEntry(repo,env,chatId,text,url)){await delIncoming(env,chatId,msg.message_id);return;}
  await telegramCall(env,'sendMessage',{chat_id:chatId,text:'از منو استفاده کنید یا یک ثبت سریع مثل «ناهار 150000» بفرستید.',reply_markup:mainKeyboard(env,url)});
}

async function handleCallback(cb,repo,env,url){
  const chatId=String(cb.message.chat.id),mid=cb.message.message_id,data=cb.data||'',finance=new FinanceService(repo,'owner');await answerCb(env,cb.id);
  if(data==='m:home'){await clearBotMode(repo);return showMain(env,chatId,mid,url);}
  if(data==='m:add')return startWizard(repo,env,chatId,mid,url,false);
  if(data==='draft:resume')return resumeWizard(repo,env,chatId,mid,url);
  if(data==='draft:discard'){await closeDraft(repo,'transaction_wizard','discarded');return showMain(env,chatId,mid,url);}
  if(data==='draft:new')return startWizard(repo,env,chatId,mid,url,true);
  if(data==='m:tx'){const rows=await repo.list('Transactions',{limit:100,includeDeleted:false,filter:x=>String(x.status||'confirmed')==='confirmed',sort:(a,b)=>String(b.transaction_date_iso).localeCompare(String(a.transaction_date_iso))});return panel(env,chatId,mid,txListText(rows),kb([[web('مشاهده کامل',webAppUrl(env,url))],[btn('⬅️ منو','m:home')]]));}
  if(data==='m:report'){const r=await currentMonthReport(repo),top=r.categories.slice(0,4).map(x=>`• ${tgEscape(x.name)}: ${moneyFa(x.amount)}`).join('\n');return panel(env,chatId,mid,`📊 <b>گزارش این ماه</b>\n\nخرج خالص: <b>${moneyFa(r.summary.net_expense)}</b>\nدرآمد: <b>${moneyFa(r.summary.income)}</b>\nکارمزد: <b>${moneyFa(r.summary.fees)}</b>\nمانده: <b>${moneyFa(r.summary.net)}</b>\n\n${top}`,kb([[web('جزئیات گزارش',webAppUrl(env,url))],[btn('⬅️ منو','m:home')]]));}
  if(data==='m:projects'){const rows=await namedRows(repo,'Projects');return panel(env,chatId,mid,'📁 <b>پروژه‌ها</b>',kb([...rows.slice(0,10).map(p=>[btn(`${p.icon||'📁'} ${p.name}`,`proj:${p.project_id}`)]),[web('مدیریت پروژه‌ها',webAppUrl(env,url))],[btn('⬅️ منو','m:home')]]));}
  if(data.startsWith('proj:')){const id=data.slice(5),p=await repo.getById('Projects',id),s=await projectSummary(repo,id);return panel(env,chatId,mid,`📁 <b>${tgEscape(p.name)}</b>\nخرج خالص: ${moneyFa(s.net_expense)}\nدرآمد: ${moneyFa(s.income)}\nکارمزد: ${moneyFa(s.fees)}\nفیش‌ها: ${s.receipt_count.toLocaleString('fa-IR')}${s.budget.amount?`\nبودجه: ${moneyFa(s.budget.used)} / ${moneyFa(s.budget.amount)}`:''}`,kb([[web('باز کردن پروژه',webAppUrl(env,url))],[btn('⬅️ پروژه‌ها','m:projects')]]));}
  if(data==='m:people'){const rows=await namedRows(repo,'People');return panel(env,chatId,mid,'👥 <b>اشخاص</b>',kb([...rows.slice(0,10).map(p=>[btn(p.name,`person:${p.person_id}`)]),[web('مدیریت اشخاص',webAppUrl(env,url))],[btn('⬅️ منو','m:home')]]));}
  if(data.startsWith('person:')){const id=data.slice(7),p=await repo.getById('People',id),s=await personSummary(repo,id),open=(s.debts||[]).filter(x=>x.status!=='settled').slice(0,4);return panel(env,chatId,mid,`👤 <b>${tgEscape(p.name)}</b>\nخرج برای شخص: ${moneyFa(s.spent)}\nدریافت از شخص: ${moneyFa(s.received)}\nطلب: ${moneyFa(s.receivable)}\nبدهی: ${moneyFa(s.debt)}\nمانده: <b>${moneyFa(s.balance)}</b>`,kb([...open.map(d=>[btn(`${d.kind==='receivable'?'طلب':'بدهی'} — ${moneyFa(Number(d.principal_amount)-Number(d.settled_amount||0))}`,`debt:view:${d.debt_id}`)]),[web('جزئیات کامل',webAppUrl(env,url))],[btn('⬅️ اشخاص','m:people')]]));}
  if(data==='m:installments'){const rows=await repo.list('Installments',{limit:500,filter:x=>x.status!=='completed'&&!bool(x.is_deleted)});return panel(env,chatId,mid,'💳 <b>اقساط</b>',kb([...rows.slice(0,10).map(p=>[btn(p.title,`inst:view:${p.installment_id}`)]),[web('مدیریت اقساط',webAppUrl(env,url))],[btn('⬅️ منو','m:home')]]));}
  if(data.startsWith('inst:view:')){const id=data.slice(10),s=await finance.installmentSummary(id);return panel(env,chatId,mid,`💳 <b>${tgEscape(s.plan.title)}</b>\nپرداخت شده: ${moneyFa(s.paid)}\nباقی‌مانده: ${moneyFa(s.remaining)}\nکارمزدها: ${moneyFa(s.fees)}\nتعداد پرداخت: ${s.payment_count.toLocaleString('fa-IR')}`,kb([[btn('➕ ثبت پرداخت',`inst:pay:${id}`),web('جزئیات',webAppUrl(env,url))],[btn('⬅️ اقساط','m:installments')]]));}
  if(data.startsWith('inst:pay:'))return startInstallmentPayment(repo,env,chatId,mid,url,data.slice(9));
  if(data.startsWith('debt:view:')){const id=data.slice(10),d=await repo.getById('Debts',id);if(!d)return;const remaining=Math.max(0,Number(d.principal_amount)-Number(d.settled_amount||0));return panel(env,chatId,mid,`👥 <b>${d.kind==='receivable'?'طلب':'بدهی'}</b>\nمانده: ${moneyFa(remaining)}\nوضعیت: ${tgEscape(d.status)}`,kb([[btn('💵 تسویه کامل',`debt:full:${id}`),btn('➗ تسویه جزئی',`debt:part:${id}`)],[web('جزئیات',webAppUrl(env,url))],[btn('⬅️ اشخاص','m:people')]]));}
  if(data.startsWith('debt:full:'))return startDebtSettlement(repo,env,chatId,mid,url,data.slice(10),true);
  if(data.startsWith('debt:part:'))return startDebtSettlement(repo,env,chatId,mid,url,data.slice(10),false);
  if(data==='m:ai'){await setBotMode(repo,{mode:'ai',message_id:mid});return panel(env,chatId,mid,'🤖 <b>دستیار مالی</b>\nسؤال یا دستور خود را بفرستید. هیچ تغییری بدون تأیید ثبت نمی‌شود.',kb([[btn('خروج از دستیار','ai:exit')]]));}
  if(data==='ai:exit'){await clearBotMode(repo);return showMain(env,chatId,mid,url);}
  if(data.startsWith('aiok:')){const id=data.slice(5);await panel(env,chatId,mid,'⏳ <b>در حال ثبت اقدام‌های تأییدشده…</b>',kb([]));try{const items=await confirmAiActions(repo,finance,id);return panel(env,chatId,mid,`✅ ${items.length.toLocaleString('fa-IR')} اقدام ثبت شد.`,kb([[btn('ادامه دستیار','m:ai'),btn('🏠 منو','m:home')]]));}catch(error){const text=String(error?.message||'').startsWith('AI_')?aiErrorText(error):userError(error);return panel(env,chatId,mid,`⚠️ ${tgEscape(text)}
پیشنهاد هنوز قابل اصلاح است.`,kb([[btn('✏️ اصلاح پیشنهاد',`aiedit:${id}`),btn('❌ لغو',`aicancel:${id}`)],[btn('ادامه دستیار','m:ai')]]));}}
  if(data.startsWith('aiedit:')){const id=data.slice(7),mode=await loadState(repo,'bot_mode');if(mode){mode.state={...mode.state,mode:'ai_edit',draft_id:id,message_id:mid};await updateDraft(repo,mode.draft,mode.state);}else await setBotMode(repo,{mode:'ai_edit',draft_id:id,message_id:mid,history:[]});return panel(env,chatId,mid,'✏️ چه چیزی را در پیشنهاد عوض کنم؟ مثلا «مبلغ را ۹۰۰ هزار کن» یا «حساب را ملت بزن».',kb([[btn('⬅️ بازگشت به پیشنهاد',`aiback:${id}`),btn('❌ لغو پیشنهاد',`aicancel:${id}`)]]));}
  if(data.startsWith('aiback:')){const id=data.slice(7);try{const current=await getAiDraft(repo,id),mode=await loadState(repo,'bot_mode');if(mode){mode.state={...mode.state,mode:'ai',draft_id:'',message_id:mid};await updateDraft(repo,mode.draft,mode.state);}return showAiResult(repo,env,chatId,mid,{kind:'actions',draft_id:id,actions:current.actions},url);}catch(error){return panel(env,chatId,mid,`⚠️ ${tgEscape(aiErrorText(error))}`,kb([[btn('ادامه دستیار','m:ai')]]));}}
  if(data.startsWith('aidel:')){const parts=data.split(':'),id=parts[1],index=Number(parts[2]);try{const changed=await removeAiAction(repo,id,index);if(!changed.actions.length)return panel(env,chatId,mid,'🗑 همه موارد پیشنهاد حذف شدند.',kb([[btn('ادامه دستیار','m:ai'),btn('🏠 منو','m:home')]]));return showAiResult(repo,env,chatId,mid,{kind:'actions',draft_id:id,actions:changed.actions},url);}catch(error){const current=await getAiDraft(repo,id).catch(()=>null);if(current?.actions?.length)return panel(env,chatId,mid,`⚠️ ${tgEscape(aiErrorText(error))}

پیشنهاد تغییری نکرد.`,kb([[btn('⬅️ نمایش پیشنهاد',`aiback:${id}`),btn('❌ لغو',`aicancel:${id}`)]]));return panel(env,chatId,mid,`⚠️ ${tgEscape(aiErrorText(error))}`,kb([[btn('ادامه دستیار','m:ai')]]));}}
  if(data.startsWith('aicancel:')){const id=data.slice(9),d=await repo.getById('Drafts',id);if(d)await repo.updateById('Drafts',id,{status:'discarded'},{action:'ai_cancel'});return panel(env,chatId,mid,'❌ پیشنهاد لغو شد.',kb([[btn('ادامه دستیار','m:ai'),btn('🏠 منو','m:home')]]));}
  if(data.startsWith('airead:p:')){const s=await personSummary(repo,data.slice(9));return panel(env,chatId,mid,`🤖 طلب باز: ${moneyFa(s.receivable)}\nبدهی باز: ${moneyFa(s.debt)}\nمانده: ${moneyFa(s.balance)}`,kb([[btn('خروج از دستیار','ai:exit')]]));}
  if(data.startsWith('airead:m:')){const tx=await queryTransactions(repo,{merchant_id:data.slice(9)}),s=summarize(tx);return panel(env,chatId,mid,`🤖 خرج خالص این فروشنده: ${moneyFa(s.net_expense)}\nتعداد تراکنش: ${tx.length.toLocaleString('fa-IR')}`,kb([[btn('خروج از دستیار','ai:exit')]]));}
  if(data.startsWith('aichoice:')){const idx=Number(data.slice(9)),choice=await loadState(repo,'ai_clarify');if(!choice)return;const selected=choice.state.options?.[idx];await repo.updateById('Drafts',choice.draft.draft_id,{status:'done'},{audit:false});const result=await handleAiText(repo,env,`${choice.state.original_text}\nانتخاب من: ${selected}`);return showAiResult(repo,env,chatId,mid,result,url,choice.state.original_text);}
  if(data==='m:settings')return panel(env,chatId,mid,'⚙️ <b>تنظیمات</b>',kb([[btn('🏷 دسته‌بندی‌ها','cat:list'),web('مدیریت کامل',webAppUrl(env,url))],[btn('🔐 رمز ورود','m:pin'),btn('🩺 سلامت سیستم','m:health')],[btn('🔒 قفل','m:lock')],[btn('⬅️ منو','m:home')]]));
  if(data==='m:pin'){const st=await pinStatus(repo,env);return panel(env,chatId,mid,`🔐 <b>رمز ورود</b>\nوضعیت: ${st.enabled?'فعال ✅':'غیرفعال ◻️'}\n\nرمز در Google Sheets به‌صورت هش ذخیره می‌شود و متن اصلی نگهداری نمی‌شود.`,kb([[btn(st.enabled?'🔁 تغییر رمز':'➕ تعیین و فعال‌سازی','pin:set')],...(st.enabled?[[btn('🚫 غیرفعال کردن رمز','pin:disable')]]:[]),[btn('⬅️ تنظیمات','m:settings')]]));}
  if(data==='pin:set'){await closeDraft(repo,'bot_input','replaced');await createDraft(repo,'bot_input',{action:'pin_set',message_id:mid},1);return panel(env,chatId,mid,'رمز جدید را بفرستید (۴ تا ۳۲ کاراکتر). پیام بعد از دریافت حذف می‌شود.',kb([[btn('⬅️ تنظیمات','m:settings')]]));}
  if(data==='pin:disable'){await disablePin(repo,env);return panel(env,chatId,mid,'✅ رمز ورود غیرفعال شد. از این به بعد ربات و Mini App برای مالک بدون رمز وارد می‌شوند.',kb([[btn('⬅️ تنظیمات','m:settings')]]));}
  if(data==='m:health'){const h=await setupHealth(repo,env);return panel(env,chatId,mid,healthText(h),kb([[btn('⬅️ تنظیمات','m:settings')]]));}
  if(data==='m:lock'){await revokeBotSessions(repo,cb.from.id);return panel(env,chatId,mid,'🔒 قفل شد. برای ورود دوباره /start را بزنید.',kb([]));}

  if(data==='cat:list')return categoryMenu(repo,env,chatId,mid);
  if(data.startsWith('cat:view:')){const id=data.slice(9),c=await repo.getById('Categories',id);return panel(env,chatId,mid,`🏷 <b>${tgEscape(c.name)}</b>`,kb([[btn('✏️ تغییر نام',`cat:rename:${id}`),btn(bool(c.favorite)?'☆ حذف از محبوب':'⭐ محبوب',`cat:fav:${id}`)],[btn('🗄 آرشیو',`cat:archive:${id}`)],[btn('⬅️ دسته‌ها','cat:list')]]));}
  if(data==='cat:new:menu'||data==='cat:new:wizard'){await closeDraft(repo,'bot_input','replaced');await createDraft(repo,'bot_input',{action:'category_new',return:data.endsWith('wizard')?'wizard':'menu',message_id:mid},24);return panel(env,chatId,mid,'نام دسته جدید را بفرستید.',kb([[btn('⬅️ بازگشت',data.endsWith('wizard')?'w:more':'cat:list')]]));}
  if(data.startsWith('cat:rename:')){await closeDraft(repo,'bot_input','replaced');await createDraft(repo,'bot_input',{action:'category_rename',category_id:data.slice(11),message_id:mid},24);return panel(env,chatId,mid,'نام جدید را بفرستید.',kb([[btn('⬅️ دسته‌ها','cat:list')]]));}
  if(data.startsWith('cat:fav:')){const id=data.slice(8),c=await repo.getById('Categories',id);await repo.updateById('Categories',id,{favorite:!bool(c.favorite)});return categoryMenu(repo,env,chatId,mid);}
  if(data.startsWith('cat:archive:')){await repo.archive('Categories',data.slice(12),true);return categoryMenu(repo,env,chatId,mid);}

  if(data.startsWith('tpl:')){const flow=await loadState(repo,'transaction_wizard'),template=await repo.getById('Templates',data.slice(4));if(!flow||!template)return;await hydrateTemplate(repo,flow.state,template);flow.state.awaiting='amount';await updateDraft(repo,flow.draft,flow.state);return askAmount(env,chatId,mid,0,flow?.state?.currency||DEFAULT_CURRENCY);}
  if(data.startsWith('w:type:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.type=data.slice(7);if(flow.state.type==='installment_payment'){flow.state.awaiting='';await updateDraft(repo,flow.draft,flow.state);return chooseInstallmentPlan(repo,env,chatId,mid,url);}flow.state.awaiting='amount';await updateDraft(repo,flow.draft,flow.state);return askAmount(env,chatId,mid,0,flow?.state?.currency||DEFAULT_CURRENCY);}
  if(data.startsWith('w:inst:')){const flow=await loadState(repo,'transaction_wizard'),plan=await repo.getById('Installments',data.slice(7));if(!flow||!plan)return;const cur=flow.state.currency||await preferredCurrency(repo);Object.assign(flow.state,{type:'installment_payment',currency:cur,installment_id:plan.installment_id,installment_title:plan.title,default_installment_amount:fromRial(Number(plan.default_installment_amount||0),cur),account_id:plan.account_id||'',person_id:plan.person_id||'',project_id:plan.project_id||'',description:plan.title,awaiting:'installment_amount'});if(plan.account_id){const a=await repo.getById('Accounts',plan.account_id);flow.state.account_name=a?.name||'';}if(plan.person_id){const p=await repo.getById('People',plan.person_id);flow.state.person_name=p?.name||'';}if(plan.project_id){const p=await repo.getById('Projects',plan.project_id);flow.state.project_name=p?.name||'';}await updateDraft(repo,flow.draft,flow.state);return askAmount(env,chatId,mid,flow.state.default_installment_amount,flow.state.currency||DEFAULT_CURRENCY);}
  if(data==='w:amount:default'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.amount=Number(flow.state.default_installment_amount||0);flow.state.awaiting='';await updateDraft(repo,flow.draft,flow.state);return afterInstallmentAmount(repo,env,chatId,mid,url,flow);}
  if(data.startsWith('w:refund:')){const flow=await loadState(repo,'transaction_wizard'),tx=await repo.getById('Transactions',data.slice(9));if(!flow||!tx)return;Object.assign(flow.state,{parent_transaction_id:tx.transaction_id,account_id:tx.account_id,category_id:tx.category_id,person_id:tx.person_id,project_id:tx.project_id,merchant_id:tx.merchant_id,description:flow.state.description||`بازپرداخت ${tx.description||''}`.trim()});for(const [sheet,key,nameKey] of [['Accounts','account_id','account_name'],['Categories','category_id','category_name'],['People','person_id','person_name'],['Projects','project_id','project_name'],['Merchants','merchant_id','merchant_name']])if(flow.state[key]){const r=await repo.getById(sheet,flow.state[key]);flow.state[nameKey]=r?.name||r?.title||'';}await updateDraft(repo,flow.draft,flow.state);return askDate(env,chatId,mid);}
  if(data.startsWith('w:acct:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;const id=data.slice(7);if(id==='none'){if(flow.state.type!=='debt')return;flow.state.account_id='';flow.state.account_name='';}else{const a=await repo.getById('Accounts',id);flow.state.account_id=id;flow.state.account_name=a?.name||'';}await updateDraft(repo,flow.draft,flow.state);if(flow.state.debt_id){flow.state.transaction_date_iso=flow.state.transaction_date_iso||parseDateInput('امروز');await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,formatTxPreview(flow.state),previewKb());}return afterAccount(repo,env,chatId,mid,url,flow);}
  if(data.startsWith('w:dest:')){const flow=await loadState(repo,'transaction_wizard'),a=await repo.getById('Accounts',data.slice(7));if(!flow||!a)return;flow.state.destination_account_id=a.account_id;flow.state.destination_account_name=a.name;await updateDraft(repo,flow.draft,flow.state);return askDate(env,chatId,mid);}
  if(data.startsWith('w:cat:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;const id=data.slice(6);if(id==='skip'){flow.state.category_id='';flow.state.category_name='';}else{const c=await repo.getById('Categories',id);flow.state.category_id=id;flow.state.category_name=c?.name||'';}await updateDraft(repo,flow.draft,flow.state);return afterCategory(repo,env,chatId,mid,flow);}
  if(data==='w:date:today'||data==='w:date:yesterday'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.transaction_date_iso=parseDateInput(data.endsWith('today')?'امروز':'دیروز');await updateDraft(repo,flow.draft,flow.state);return afterDate(repo,env,chatId,mid,flow);}
  if(data==='w:date:manual'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting='date';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,'تاریخ شمسی مثل 1405/05/18 یا میلادی مثل 2026/08/09 را بفرستید.',kb([[btn('❌ لغو','w:cancel')]]));}
  if(data==='w:time:now'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.transaction_time=tehranTime();await updateDraft(repo,flow.draft,flow.state);return afterTime(repo,env,chatId,mid,flow);}
  if(data==='w:time:manual'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting='time';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,'ساعت را مثل 16:05 یا 16:05:30 بفرستید.',kb([[btn('❌ لغو','w:cancel')]]));}
  if(data==='w:desc:skip'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.description=flow.state.description||'';flow.state.awaiting='';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,formatTxPreview(flow.state),previewKb());}
  if(data==='w:preview'){const flow=await loadState(repo,'transaction_wizard');if(flow)return panel(env,chatId,mid,formatTxPreview(flow.state),previewKb());}
  if(data==='w:more'){const flow=await loadState(repo,'transaction_wizard');if(flow)return showAdvanced(repo,env,chatId,mid,flow.state);}
  if(data==='w:more:person')return choosePeople(repo,env,chatId,mid,'advanced');
  if(data==='w:more:project')return showEntityChoices(repo,env,chatId,mid,'Projects','project_id','w:project:','📁 پروژه','w:new:project','w:project:clear');
  if(data==='w:more:merchant')return showEntityChoices(repo,env,chatId,mid,'Merchants','merchant_id','w:merchant:','🏪 فروشنده','w:new:merchant','w:merchant:clear');
  if(data==='w:more:tags'){const flow=await loadState(repo,'transaction_wizard');if(flow)return showTags(repo,env,chatId,mid,flow.state);}
  if(data.startsWith('w:person:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;const id=data.slice(9);if(id==='clear'){flow.state.person_id='';flow.state.person_name='';await updateDraft(repo,flow.draft,flow.state);return showAdvanced(repo,env,chatId,mid,flow.state);}const p=await repo.getById('People',id);flow.state.person_id=id;flow.state.person_name=p?.name||'';await updateDraft(repo,flow.draft,flow.state);const context=['debt','receivable'].includes(flow.state.type)&&!flow.state.account_id?'core':'advanced';return afterPerson(repo,env,chatId,mid,url,flow,context);}
  if(data.startsWith('w:newperson:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting=data.endsWith('advanced')?'new_person_advanced':'new_person_core';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,'نام شخص جدید را بفرستید.',kb([[btn('⬅️ بازگشت','w:more')]]));}
  if(data==='w:personreturn:yes'||data==='w:personreturn:no'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;if(data.endsWith('yes'))flow.state.type='receivable';await updateDraft(repo,flow.draft,flow.state);return showAdvanced(repo,env,chatId,mid,flow.state);}
  if(data.startsWith('w:project:')||data.startsWith('w:merchant:')){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;const project=data.startsWith('w:project:'),id=data.slice(project?10:11);if(id==='clear'){if(project){flow.state.project_id='';flow.state.project_name='';}else{flow.state.merchant_id='';flow.state.merchant_name='';}}else{const row=await repo.getById(project?'Projects':'Merchants',id);if(!row)return;if(project){flow.state.project_id=id;flow.state.project_name=row.name||'';}else{flow.state.merchant_id=id;flow.state.merchant_name=row.name||'';}}await updateDraft(repo,flow.draft,flow.state);return showAdvanced(repo,env,chatId,mid,flow.state);}
  if(data==='w:new:project'||data==='w:new:merchant'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting=data.endsWith('project')?'new_project':'new_merchant';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,'نام را بفرستید.',kb([[btn('⬅️ بازگشت','w:more')]]));}
  if(data.startsWith('w:tag:')){const flow=await loadState(repo,'transaction_wizard'),tag=await repo.getById('Tags',data.slice(6));if(!flow||!tag)return;const selected=new Set(flow.state.tag_ids||[]);selected.has(tag.tag_id)?selected.delete(tag.tag_id):selected.add(tag.tag_id);flow.state.tag_ids=[...selected];const all=await repo.list('Tags',{limit:500});flow.state.tag_names=all.filter(x=>selected.has(x.tag_id)).map(x=>x.name);await updateDraft(repo,flow.draft,flow.state);return showTags(repo,env,chatId,mid,flow.state);}
  if(['w:more:fee','w:more:note','w:more:tracking','w:more:reference'].includes(data)){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting={['w:more:fee']:'fee_amount',['w:more:note']:'note',['w:more:tracking']:'tracking_number',['w:more:reference']:'reference_number'}[data];await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,'مقدار را بفرستید.',kb([[btn('⬅️ بازگشت','w:more')]]));}
  if(data==='w:more:receipt'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting='receipt';await updateDraft(repo,flow.draft,flow.state);return showReceiptCapture(env,chatId,mid,flow.state);}
  if(data==='w:receipt:done'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting='';await updateDraft(repo,flow.draft,flow.state);return showAdvanced(repo,env,chatId,mid,flow.state);}
  if(data==='w:edit')return panel(env,chatId,mid,'✏️ <b>کدام بخش؟</b>',kb([[btn('مبلغ','w:edit:amount'),btn('حساب','w:edit:account')],[btn('دسته','w:edit:category'),btn('تاریخ','w:edit:date')],[btn('ساعت','w:edit:time'),btn('توضیح','w:edit:description')],[btn('جزئیات بیشتر','w:more')],[btn('⬅️ پیش‌نمایش','w:preview')]]));
  if(data==='w:edit:amount'||data==='w:edit:description'){const flow=await loadState(repo,'transaction_wizard');if(!flow)return;flow.state.awaiting=data.endsWith('amount')?'amount':'description';await updateDraft(repo,flow.draft,flow.state);return panel(env,chatId,mid,data.endsWith('amount')?'مبلغ جدید را بفرستید.':'توضیح جدید را بفرستید.',kb([[btn('⬅️ پیش‌نمایش','w:preview')]]));}
  if(data==='w:edit:account')return chooseAccounts(repo,env,chatId,mid,url);
  if(data==='w:edit:category')return chooseCategories(repo,env,chatId,mid);
  if(data==='w:edit:date')return askDate(env,chatId,mid);
  if(data==='w:edit:time')return askTime(env,chatId,mid);
  if(data==='w:cancel'){await closeDraft(repo,'transaction_wizard','cancelled');return showMain(env,chatId,mid,url);}
  if(data==='w:confirm')return confirmWizard(repo,finance,env,chatId,mid,url);

  if(data.startsWith('rec:post:'))return startRecurring(repo,env,chatId,mid,url,data.slice(9));
  if(data.startsWith('rec:skip:')){const item=await repo.getById('Recurring',data.slice(9));if(item)await repo.updateById('Recurring',item.recurring_id,{next_due_date:advancePastDate(item.next_due_date||tehranToday(),item.frequency,item.custom_json,tehranToday())});return panel(env,chatId,mid,'⏭ این نوبت رد شد.',kb([[btn('🏠 منو','m:home')]]));}
  if(data.startsWith('receiptai:create:'))return receiptInboxToWizard(repo,env,chatId,mid,url,data.slice(17));
  if(data.startsWith('receiptai:discard:')){const item=await repo.getById('Inbox',data.slice(18)),payload=safeJsonParse(item?.payload_json,{});if(payload.object_key&&hasR2(env))await deletePrivate(env,payload.object_key);if(item)await repo.updateById('Inbox',item.inbox_id,{status:'dismissed'});return panel(env,chatId,mid,'❌ فیش کنار گذاشته شد.',kb([[btn('🏠 منو','m:home')]]));}
  if(data.startsWith('impacct:'))return processTelegramCsv(repo,env,chatId,mid,url,data.slice(8));
}

async function startInstallmentPayment(repo,env,chatId,mid,url,id){await closeDraft(repo,'transaction_wizard','replaced');const plan=await repo.getById('Installments',id);if(!plan||bool(plan.is_deleted))throw new Error('NOT_FOUND');const currency=await preferredCurrency(repo),state={type:'installment_payment',currency,installment_id:id,installment_title:plan.title,default_installment_amount:fromRial(Number(plan.default_installment_amount||0),currency),account_id:plan.account_id||'',person_id:plan.person_id||'',project_id:plan.project_id||'',description:plan.title,fee_amount:0,tag_ids:[],tag_names:[],pending_receipts:[],message_id:mid,awaiting:'installment_amount'};if(state.account_id){const a=await repo.getById('Accounts',state.account_id);state.account_name=a?.name||'';}await createDraft(repo,'transaction_wizard',state);return askAmount(env,chatId,mid,state.default_installment_amount,currency);}
async function startDebtSettlement(repo,env,chatId,mid,url,id,full){await closeDraft(repo,'transaction_wizard','replaced');const debt=await repo.getById('Debts',id);if(!debt||bool(debt.is_deleted))throw new Error('NOT_FOUND');const currency=await preferredCurrency(repo),remainingStored=Math.max(0,Number(debt.principal_amount)-Number(debt.settled_amount||0)),remaining=fromRial(remainingStored,currency),person=debt.person_id?await repo.getById('People',debt.person_id):null,state={type:debt.kind==='receivable'?'income':'debt',currency,debt_id:id,settlement_kind:debt.kind,person_id:debt.person_id,person_name:person?.name||'',project_id:debt.project_id||'',amount:full?remaining:undefined,fee_amount:0,description:debt.kind==='receivable'?'دریافت طلب':'پرداخت بدهی',transaction_date_iso:parseDateInput('امروز'),tag_ids:[],tag_names:[],pending_receipts:[],message_id:mid,awaiting:full?'':'debt_partial_amount'};await createDraft(repo,'transaction_wizard',state);if(full)return chooseAccounts(repo,env,chatId,mid,url);return askAmount(env,chatId,mid,0,currency);}
async function startRecurring(repo,env,chatId,mid,url,id){await closeDraft(repo,'transaction_wizard','replaced');const item=await repo.getById('Recurring',id);if(!item||bool(item.is_deleted))throw new Error('NOT_FOUND');const currency=await preferredCurrency(repo),state={type:item.type,currency,amount:fromRial(Number(item.amount),currency),account_id:item.account_id||'',category_id:item.category_id||'',person_id:item.person_id||'',project_id:item.project_id||'',merchant_id:item.merchant_id||'',description:item.title,transaction_date_iso:parseDateInput('امروز'),fee_amount:0,recurring_id:id,tag_ids:[],tag_names:[],pending_receipts:[],message_id:mid};for(const [sheet,key,nameKey] of [['Accounts','account_id','account_name'],['Categories','category_id','category_name'],['People','person_id','person_name'],['Projects','project_id','project_name'],['Merchants','merchant_id','merchant_name']])if(state[key]){const r=await repo.getById(sheet,state[key]);state[nameKey]=r?.name||r?.title||'';}await createDraft(repo,'transaction_wizard',state);if(!state.account_id&&['expense','income','receivable'].includes(state.type))return chooseAccounts(repo,env,chatId,mid,url);return panel(env,chatId,mid,formatTxPreview(state),previewKb());}

async function confirmWizard(repo,finance,env,chatId,mid,url){
  const flow=await loadState(repo,'transaction_wizard');if(!flow)return;const s=flow.state;
  if(!s.type||!Number.isSafeInteger(Number(s.amount))||Number(s.amount)<=0)throw new Error('VALIDATION');
  if(['expense','income','transfer','installment_payment','receivable','refund'].includes(s.type)&&!s.account_id)throw new Error('VALIDATION');
  if(['debt','receivable'].includes(s.type)&&!s.person_id&&!s.debt_id)throw new Error('VALIDATION');
  if(s.type==='transfer'&&!s.destination_account_id)throw new Error('VALIDATION');if(s.type==='refund'&&!s.parent_transaction_id)throw new Error('VALIDATION');
  const result=await repo.idempotent(`wizard:${flow.draft.draft_id}`,'telegram',async()=>{
    let transaction;
    if(s.installment_id)transaction=(await finance.payInstallment(s.installment_id,{amount:Number(s.amount),fee_amount:Number(s.fee_amount||0),account_id:s.account_id,date:s.transaction_date_iso||parseDateInput('امروز'),transaction_time:s.transaction_time||tehranTime(),note:s.note||'',source:'installment',currency:s.currency||DEFAULT_CURRENCY})).transaction;
    else if(s.debt_id)transaction=(await finance.settleDebt(s.debt_id,{amount:Number(s.amount),fee_amount:Number(s.fee_amount||0),account_id:s.account_id,date:s.transaction_date_iso||parseDateInput('امروز'),transaction_time:s.transaction_time||tehranTime(),note:s.note||'',source:'telegram',currency:s.currency||DEFAULT_CURRENCY})).transaction;
    else if(s.type==='receivable')transaction=(await finance.createReceivable({...s,date:s.transaction_date_iso,receipt_count:0,source:s.recurring_id?'recurring':'telegram'})).transaction;
    else if(s.type==='debt')transaction=(await finance.createDebt({...s,date:s.transaction_date_iso,receipt_count:0,source:s.recurring_id?'recurring':'telegram'})).transaction;
    else transaction=await finance.createTransaction({...s,receipt_count:0,tag_ids:s.tag_ids},s.recurring_id?'recurring':'telegram');
    if(s.tag_ids?.length&&(s.installment_id||s.debt_id||s.type==='receivable'||s.type==='debt'))for(const tagId of s.tag_ids){const exists=await repo.findOne('EntityTags',x=>x.entity_type==='transaction'&&x.entity_id===transaction.transaction_id&&x.tag_id===tagId);if(!exists)await repo.insert('EntityTags',{entity_tag_id:uuid(),entity_type:'transaction',entity_id:transaction.transaction_id,tag_id:tagId,created_at:nowIso(),schema_version:SCHEMA_VERSION});}
    const keep=await repo.setting('keep_original_receipts',false);for(const pending of s.pending_receipts||[]){const object=await getPrivate(env,pending.key);if(!object)continue;const bytes=await object.arrayBuffer();await saveReceipt(repo,env,{transaction_id:transaction.transaction_id,bytes,mime_type:pending.mime||'image/jpeg',source:'telegram',keepOriginal:keep,originalBytes:keep?bytes:null});await deletePrivate(env,pending.key);}
    if(s.receipt_inbox_id){const inbox=await repo.getById('Inbox',s.receipt_inbox_id);if(inbox)await repo.updateById('Inbox',inbox.inbox_id,{status:'done'});}
    if(s.recurring_id){const recurring=await repo.getById('Recurring',s.recurring_id);if(recurring)await repo.updateById('Recurring',recurring.recurring_id,{next_due_date:advancePastDate(recurring.next_due_date||tehranToday(),recurring.frequency,recurring.custom_json,tehranToday())});}
    return{transaction};
  });
  await repo.updateById('Drafts',flow.draft.draft_id,{status:'confirmed'},{audit:false});const currency=s.currency||await preferredCurrency(repo);return panel(env,chatId,mid,`✅ ثبت شد\n${moneyFa(result.transaction.amount,currency)}${result.transaction.fee_amount?`\nکارمزد: ${moneyFa(result.transaction.fee_amount,currency)}`:''}`,kb([[btn('➕ ثبت جدید','m:add'),btn('🏠 منو','m:home')]]));
}

function aiInputMoney(x){const cur=currencyCode(x.currency||DEFAULT_CURRENCY),stored=toRial(Number(x.amount||0),cur);return moneyFa(stored,cur);}
async function formatAiAction(repo,action,index){const x=action.data||{};if(action.action==='create_transaction')return`${index}. ${TYPES[x.type]||'تراکنش'} ${x.amount?aiInputMoney(x):''}${x.transaction_time?` • ${tgEscape(x.transaction_time)}`:''}${x.description?` — ${tgEscape(x.description)}`:''}`;if(action.action==='create_person')return`${index}. ساخت شخص: ${tgEscape(x.name||'')}`;if(action.action==='create_project')return`${index}. ساخت پروژه: ${tgEscape(x.name||'')}`;if(action.action==='edit_transaction')return`${index}. ✏️ ویرایش تراکنش ${tgEscape(String(x.transaction_id||'').slice(0,8))}`;if(action.action==='delete_transaction')return`${index}. 🗑 حذف تراکنش ${tgEscape(String(x.transaction_id||'').slice(0,8))}`;if(action.action==='pay_installment'){const p=x.installment_id?await repo.getById('Installments',x.installment_id):null;return`${index}. پرداخت قسط ${tgEscape(p?.title||'')}${x.amount?` — ${aiInputMoney(x)}`:''}`;}if(action.action==='settle_debt')return`${index}. تسویه ${x.amount?aiInputMoney(x):''}`;return`${index}. اقدام مالی`;}

async function showAiResult(repo,env,chatId,mid,result,url,originalText=''){
  if(result.kind==='actions'){const lines=[];for(let i=0;i<result.actions.length;i++)lines.push(await formatAiAction(repo,result.actions[i],i+1));const removeRows=result.actions.slice(0,8).map((_,i)=>[btn(`🗑 حذف مورد ${i+1}`,`aidel:${result.draft_id}:${i}`)]);return panel(env,chatId,mid,`🤖 <b>${result.actions.length.toLocaleString('fa-IR')} اقدام پیشنهادی</b>\n\n${lines.join('\n')}\n\nقبل از ثبت می‌توانی پیشنهاد را اصلاح یا یک مورد را حذف کنی.`,kb([[btn('✅ تأیید همه',`aiok:${result.draft_id}`),btn('✏️ اصلاح',`aiedit:${result.draft_id}`)],...removeRows,[btn('❌ لغو همه',`aicancel:${result.draft_id}`),btn('خروج از دستیار','ai:exit')]]));}
  if(result.kind==='split'){const rows=result.result.items.map(x=>`${tgEscape(x.name)} | پرداخت ${moneyFa(x.paid_amount)} | سهم ${moneyFa(x.share_amount)} | مانده ${moneyFa(x.balance)}`).join('\n'),settles=result.result.settlements.map(x=>`${tgEscape(x.from.name)} → ${tgEscape(x.to.name)}: ${moneyFa(x.amount)}`).join('\n');return panel(env,chatId,mid,`🤖 <b>دنگ</b>\n${rows}\n\n${settles||'تسویه‌ای لازم نیست.'}`,kb([[web('ذخیره/تبدیل به طلب',webAppUrl(env,url))],[btn('خروج از دستیار','ai:exit')]]));}
  if(result.kind==='clarify'&&Array.isArray(result.options)&&result.options.length){
    if(result.entity==='person'||result.entity==='merchant'){const prefix=result.entity==='person'?'airead:p:':'airead:m:',buttons=result.options.slice(0,8).map(o=>[btn(o.name||String(o),`${prefix}${o.id}`)]);buttons.push([btn('خروج از دستیار','ai:exit')]);return panel(env,chatId,mid,`🤖 ${tgEscape(result.text)}`,kb(buttons));}
    await closeDraft(repo,'ai_clarify','replaced');await createDraft(repo,'ai_clarify',{original_text:originalText,options:result.options},2);const buttons=result.options.slice(0,8).map((o,i)=>[btn(String(o).slice(0,48),`aichoice:${i}`)]);buttons.push([btn('خروج از دستیار','ai:exit')]);return panel(env,chatId,mid,`🤖 ${tgEscape(result.text)}`,kb(buttons));
  }
  return panel(env,chatId,mid,`🤖 ${tgEscape(sanitizeAiText(result.text||'انجام شد.'))}`,kb([[btn('خروج از دستیار','ai:exit'),web('جزئیات',webAppUrl(env,url))]]));
}

async function addPendingReceipt(msg,repo,env,url,fileId,mimeHint='image/jpeg'){
  const chatId=String(msg.chat.id),flow=await loadState(repo,'transaction_wizard');if(!flow||flow.state.awaiting!=='receipt')return false;if(!hasR2(env)){await panel(env,chatId,flow.state.message_id,'⚠️ فضای فایل تنظیم نشده است.',kb([[btn('⬅️ بازگشت','w:more')]]));return true;}const file=await downloadTelegramFile(env,fileId),key=`inbox/receipt/${new Date().getUTCFullYear()}/${uuid()}`;await putPrivate(env,key,file.bytes,{contentType:file.mime||mimeHint,cacheControl:'private, max-age=0'});flow.state.pending_receipts=[...(flow.state.pending_receipts||[]),{key,mime:file.mime||mimeHint}];await updateDraft(repo,flow.draft,flow.state);await delIncoming(env,chatId,msg.message_id);await showReceiptCapture(env,chatId,flow.state.message_id,flow.state);return true;
}
async function handlePhoto(msg,repo,env,url){const photo=msg.photo[msg.photo.length-1];if(await addPendingReceipt(msg,repo,env,url,photo.file_id,'image/jpeg'))return;const chatId=String(msg.chat.id);if(!hasR2(env)){await telegramCall(env,'sendMessage',{chat_id:chatId,text:'⚠️ فضای فایل تنظیم نشده است.'});return;}const file=await downloadTelegramFile(env,photo.file_id),key=`inbox/receipt/${new Date().getUTCFullYear()}/${uuid()}.jpg`;await putPrivate(env,key,file.bytes,{contentType:file.mime||'image/jpeg',cacheControl:'private, max-age=0'});let ai=null;try{const caps=await getCapabilities(repo,env);if(caps.vision)ai=await extractReceipt(repo,env,file.bytes,file.mime||'image/jpeg');}catch{}const inbox=await repo.insert('Inbox',{inbox_id:uuid(),type:'receipt_ai',entity_type:'receipt_inbox',entity_id:'',title:'فیش ارسالی',payload_json:JSON.stringify({object_key:key,mime_type:file.mime||'image/jpeg',ai}),status:'pending',created_at:nowIso(),updated_at:nowIso(),schema_version:SCHEMA_VERSION});await delIncoming(env,chatId,msg.message_id);const text=ai?`🧾 <b>پیشنهاد از روی فیش</b>\nمبلغ: ${ai.amount?moneyFa(ai.amount):'—'}\nتاریخ: ${tgEscape(ai.date||'—')}\nفروشنده: ${tgEscape(ai.merchant||'—')}\nکارمزد: ${ai.fee?moneyFa(ai.fee):'—'}\nپیگیری: ${tgEscape(ai.tracking_number||'—')}\nمرجع: ${tgEscape(ai.reference_number||'—')}\nشرح: ${tgEscape(ai.description||'—')}`:'🧾 فیش ذخیره شد. مدل Vision در دسترس نیست؛ ثبت را می‌توانید دستی ادامه دهید.';await telegramCall(env,'sendMessage',{chat_id:chatId,text,parse_mode:'HTML',reply_markup:kb([[btn('✅ ادامه ثبت',`receiptai:create:${inbox.inbox_id}`),web('✏️ اصلاح',webAppUrl(env,url))],[btn('❌ لغو',`receiptai:discard:${inbox.inbox_id}`)]])});}
async function receiptInboxToWizard(repo,env,chatId,mid,url,id){const inbox=await repo.getById('Inbox',id),payload=safeJsonParse(inbox?.payload_json,{}),x=payload.ai||{};await closeDraft(repo,'transaction_wizard','replaced');const state={type:'expense',amount:x.amount||undefined,fee_amount:x.fee||0,transaction_date_iso:x.date?parseDateInput(x.date):parseDateInput('امروز'),description:x.description||'',tracking_number:x.tracking_number||'',reference_number:x.reference_number||'',merchant_name:x.merchant||'',pending_receipts:[{key:payload.object_key,mime:payload.mime_type||'image/jpeg'}],receipt_inbox_id:id,message_id:mid,tag_ids:[],tag_names:[]};await createDraft(repo,'transaction_wizard',state);const flow=await loadState(repo,'transaction_wizard');if(!state.amount){flow.state.awaiting='amount';await updateDraft(repo,flow.draft,flow.state);return askAmount(env,chatId,mid,0,flow?.state?.currency||DEFAULT_CURRENCY);}return afterAmount(repo,env,chatId,mid,url,flow);}

async function handleDocument(msg,repo,env,url){
  const doc=msg.document,chatId=String(msg.chat.id),isImage=String(doc.mime_type||'').startsWith('image/');if(isImage&&await addPendingReceipt(msg,repo,env,url,doc.file_id,doc.mime_type))return;if(!hasR2(env)){await telegramCall(env,'sendMessage',{chat_id:chatId,text:'⚠️ فضای فایل برای Inbox تنظیم نشده است.'});return;}const file=await downloadTelegramFile(env,doc.file_id),imp=await saveInboxFile(repo,env,{name:doc.file_name||'file',bytes:file.bytes,mime_type:doc.mime_type||file.mime,source:'telegram'});await delIncoming(env,chatId,msg.message_id);const csv=(doc.file_name||'').toLowerCase().endsWith('.csv')||String(doc.mime_type||'').includes('csv');if(csv){const message=await telegramCall(env,'sendMessage',{chat_id:chatId,text:'📥 فایل CSV دریافت شد. حساب صورتحساب را انتخاب کنید.'});await closeDraft(repo,'import_flow','replaced');await createDraft(repo,'import_flow',{import_id:imp.import_id,message_id:message.message_id},24);const accounts=await namedRows(repo,'Accounts');return panel(env,chatId,message.message_id,'📥 <b>حساب صورتحساب</b>',kb([...accounts.slice(0,12).map(a=>[btn(a.name,`impacct:${a.account_id}`)]),[web('بررسی در Mini App',webAppUrl(env,url))]]));}return telegramCall(env,'sendMessage',{chat_id:chatId,text:'📥 فایل به Inbox اضافه شد.',reply_markup:kb([[web('بررسی در Mini App',webAppUrl(env,url))]])});
}
async function processTelegramCsv(repo,env,chatId,mid,url,accountId){const flow=await loadState(repo,'import_flow');if(!flow)return;const imp=await repo.getById('Imports',flow.state.import_id),object=await getPrivate(env,imp.object_key);if(!object)throw new Error('NOT_FOUND');const text=new TextDecoder().decode(await object.arrayBuffer()),rows=rowsFromCsv(text),preview=await previewImport(repo,{file_name:imp.file_name,account_id:accountId,rows,source:'telegram'});await repo.updateById('Drafts',flow.draft.draft_id,{status:'done'},{audit:false});return panel(env,chatId,mid,`📥 <b>نتیجه بررسی</b>\nکل: ${preview.counts.total.toLocaleString('fa-IR')}\nجدید: ${preview.counts.new.toLocaleString('fa-IR')}\nتکراری: ${preview.counts.duplicate.toLocaleString('fa-IR')}\nمشکوک: ${preview.counts.suspect.toLocaleString('fa-IR')}\nنامعتبر: ${preview.counts.invalid.toLocaleString('fa-IR')}`,kb([[web('بررسی و تأیید در Mini App',webAppUrl(env,url))],[btn('🏠 منو','m:home')]]));}

async function handleVoice(msg,repo,env,url){const chatId=String(msg.chat.id);let text;try{const file=await downloadTelegramFile(env,msg.voice.file_id);text=await transcribeAudio(repo,env,file.bytes,'ogg');}catch{await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🎙 مدل صوتی تنظیم نشده یا در دسترس نیست.'});return;}await delIncoming(env,chatId,msg.message_id);let mode=await loadState(repo,'bot_mode');if(!mode||mode.state.mode!=='ai'){const message=await telegramCall(env,'sendMessage',{chat_id:chatId,text:'🤖 پیام صوتی پردازش شد. حالت دستیار فعال شد.'});await setBotMode(repo,{mode:'ai',message_id:message.message_id});mode=await loadState(repo,'bot_mode');}const result=await handleAiText(repo,env,text);return showAiResult(repo,env,chatId,mode.state.message_id,result,url,text);}
